---
kind: pipeline
type: docker
name: build-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: download-linux-amd64
  image: registry.suse.com/suse/sle15:15.3.17.8.1
  environment:
    ARCH: amd64
  commands:
    - zypper -n install curl jq git
    - scripts/download
    -
- name: build-linux-amd64
  image: plugins/docker
  settings:
    purge: false
    dry_run: true
    build_args:
      - ARCH=amd64
      - "VERSION=${DRONE_TAG/+/-}"
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/system-agent-installer-rke2
    tag: "${DRONE_COMMIT/+/-}-linux-amd64"
    username:
      from_secret: docker_username
  when:
    event:
      - pull_request

- name: publish-linux-amd64
  image: plugins/docker
  settings:
    purge: false
    build_args:
      - ARCH=amd64
      - "VERSION=${DRONE_TAG/+/-}"
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/system-agent-installer-rke2
    tag: "${DRONE_TAG/+/-}-linux-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/tags/*
    event:
      - tag
---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64
depends_on:
  - build-linux-amd64

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  volumes:
    - name: docker
      path: /var/run/docker.sock
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/tags/*
    event:
      - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

