FROM debian:buster

ENV ARCH amd64

RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates gnupg wget curl

RUN wget -O - https://download.docker.com/linux/debian/gpg | apt-key add - && \
    echo "deb [arch=${ARCH}] https://download.docker.com/linux/debian buster stable" >> /etc/apt/sources.list && \
    cat /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y docker-ce bash git jq

ENV DAPPER_ENV REPO TAG DRONE_TAG CROSS
ENV DAPPER_SOURCE /go/src/github.com/rancher/system-agent-installer-rke2/
ENV DAPPER_OUTPUT ./bin ./dist
ENV DAPPER_DOCKER_SOCKET true
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["build"]
