#!/bin/bash

source $(dirname $0)/version

cd $(dirname $0)/..

# This script serves to download/stage the installer

mkdir -p tmp

curl -sfL https://get.rke2.io > tmp/install.sh
chmod +x tmp/install.sh
