#!/bin/bash
set -x

source $(dirname $0)/version

cd $(dirname $0)/..

# This script serves to download/stage the installer

mkdir -p tmp

curl -sfL https://raw.githubusercontent.com/Oats87/rke2/issues/rke2/795/install.sh > tmp/installer.sh
chmod +x tmp/installer.sh

mkdir -p tmp/artifacts
cd tmp/artifacts
curl -fL -O https://github.com/rancher/rke2/releases/download/${URI_VERSION}/rke2.linux-amd64.tar.gz
curl -fL -O https://github.com/rancher/rke2/releases/download/${URI_VERSION}/sha256sum-amd64.txt