#!/bin/bash
set -x

source $(dirname $0)/version

cd $(dirname $0)/..

# This script serves to download/stage the installer

mkdir -p artifacts

if [ -z "${LOCAL_ARTIFACTS}" ]; then
    curl -fL https://raw.githubusercontent.com/rancher/rke2/master/install.sh > artifacts/install.sh
    chmod +x artifacts/install.sh

    if [[ "${ARCH}" = "arm64" ]] && [[ "${VERSION}" =~ ^v1\.(20|24|25|26)\. ]]; then
        echo "Skipping arm64 - not supported for this version."
        exit
    fi
else
    cp local/* artifacts
    chmod +x artifacts/install.sh
fi
