#!/bin/bash
set -x

source $(dirname $0)/version

cd $(dirname $0)/..

# This script serves to download/stage the installer

mkdir -p tmp

curl -sfL https://raw.githubusercontent.com/rancher/rke2/master/install.sh > tmp/installer.sh
chmod +x tmp/installer.sh

if [ -z "${LOCAL_ARTIFACTS}" ]; then
    mkdir -p artifacts
    cd artifacts
    curl -fL -O https://github.com/rancher/rke2/releases/download/${URI_VERSION}/rke2.linux-amd64.tar.gz
    curl -fL -O https://github.com/rancher/rke2/releases/download/${URI_VERSION}/sha256sum-amd64.txt
fi