#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts

IMAGE=${REPO}/system-agent-installer-rke2:${VERSION}
DOCKERFILE=package/Dockerfile

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
