name: Create Tag on Dispatch

on: [repository_dispatch]
jobs:
  Create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for creating the GH release
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Github App secrets out of vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/github/app-credentials appId | APP_ID ;
            secret/data/github/repo/${{ github.repository }}/github/app-credentials privateKey | PRIVATE_KEY ;

      - name: Generate short-lived github app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.PRIVATE_KEY }}

      - name: Create Release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh release create "${{ github.event.client_payload.tag }}" --title "Release ${{ github.event.client_payload.tag }}"
